---
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

#- name: Install collection posix.selinux
#  community.ansible_galaxy_install:
#    type: collection
#    name: posix.selinux

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

#- name: Disable SeLinux
#  ansible.posix.selinux:
#    state: disabled

- name: Copy nginx configuration
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: nginx service state
  service:
    name: nginx
    state: started
    enabled: yes

...
